Implement smithing table (but only works in Creative mode :/)
PowerNukkit/PowerNukkit pull request #648
Opened 2020-09-29 03:45 UTC by joserobjr

In survival mode, the client is sending inventory mismatch when attempting to get a netherite pickaxe and I have no idea why yet.

2020-12-15 16:35 UTC, PocketMiner82 commented
@joserobjr Maybe this will help you: https://github.com/GeyserMC/Geyser/pull/1360

2020-12-26 20:39 UTC, Camotoy commented
To my understanding, without switching to the new inventory system you will get INVENTORY_MISMATCH when attempting to take an item out of the smithing table's output.

2021-02-14 23:22 UTC, joserobjr commented
I think I'm going to do the same hack as geyser

2021-02-15 00:18 UTC, Camotoy commented
Geyser is not implementing this hack - instead, we're working on implementing the new inventory system that allows the smithing table to work.

2021-05-17 02:38 UTC, LoboMetalurgico requested changes
Helo! Thank you for your Pull Request. It is really very good and contains only a few annotation problems. Could you fix them?

2021-05-17 02:38 UTC, LoboMetalurgico commented on src/main/java/cn/nukkit/inventory/CraftingManager.java
> +    private void registerSmithingRecipes() {
Missing @PowerNukkitOnly

2021-05-17 02:38 UTC, LoboMetalurgico commented on src/main/java/cn/nukkit/inventory/CraftingManager.java
> +    private boolean matchItemsAccumulation(SmithingRecipe recipe, List<Item> inputList, Item primaryOutput) {
Missing @PowerNukkitOnly or @PowerNukkitDifference

2021-05-17 02:38 UTC, LoboMetalurgico commented on src/main/java/cn/nukkit/inventory/InventoryType.java
> +    SMITHING_TABLE(2, "Smithing Table", 33);
Missing @PowerNukkitOnly

2021-05-17 02:38 UTC, LoboMetalurgico commented on src/main/java/cn/nukkit/inventory/CraftingManager.java
> +    private final Int2ObjectOpenHashMap<Map<UUID, SmithingRecipe>> smithingRecipes = new Int2ObjectOpenHashMap<>();
Missing @PowerNukkitOnly

2021-05-17 02:38 UTC, LoboMetalurgico commented on src/main/java/cn/nukkit/inventory/SmithingInventory.java
> +    public void onSlotChange(int index, Item before, boolean send) {
Missing @PowerNukkitOnly

2021-05-17 02:38 UTC, LoboMetalurgico commented on src/main/java/cn/nukkit/inventory/SmithingInventory.java
> +    private void setResult(Item result) {
Missing @PowerNukkitOnly

2021-05-17 02:38 UTC, LoboMetalurgico commented on src/main/java/cn/nukkit/inventory/transaction/action/InventoryAction.java
> +@ToString
Need to be @ToString(callSuper = true)

2021-05-17 02:44 UTC, LoboMetalurgico approved these changes
Thank You!

2021-05-17 02:46 UTC, merged