Update Pumpkin
PowerNukkit/PowerNukkit pull request #663
Opened 2020-10-04 04:06 UTC by good777LUCKY

Update pumpkin to use the new block state system and add a carve behavior. (Add #662)

2020-10-08 00:53 UTC, LoboMetalurgico approved these changes
Thanks for your Pull Request

2020-10-08 01:13 UTC, LoboMetalurgico requested changes
During the test of the game, I noticed that the pumpkins disintegrate as soon as they are activated by the redstone. Could you investigate this, please?

2020-10-09 04:10 UTC, good777LUCKY commented
> During the test of the game, I noticed that the pumpkins disintegrate as soon as they are activated by the redstone. Could you investigate this, please?

I fix it.

2020-10-14 03:23 UTC, LoboMetalurgico submitted a review, later dismissed
Thanks for the correction. I found some more simple things that need to be fixed before we merge.

2020-10-14 03:23 UTC, LoboMetalurgico commented on src/main/java/cn/nukkit/block/BlockPumpkin.java
> +import cn.nukkit.block.BlockCarvedPumpkin;
This import is not being used (cn.nukkit.block.BlockCarvedPumpkin). Could you remove it?

2020-10-14 03:23 UTC, LoboMetalurgico commented on src/main/java/cn/nukkit/block/BlockPumpkin.java
> +import cn.nukkit.item.ItemSeedsPumpkin;
This import (cn.nukkit.item.ItemSeedsPumpkin) is not being used. Could you remove it?

2020-10-14 03:23 UTC, LoboMetalurgico commented on src/main/java/cn/nukkit/block/BlockPumpkin.java
> +    public BlockProperties getProperties() {
This function requires the @Nonnull annotation

2020-10-14 03:27 UTC, LoboMetalurgico requested changes
Thanks for the correction. I found some more simple things that need to be fixed before we merge.

2020-10-14 03:37 UTC, good777LUCKY commented
> Thanks for the correction. I found some more simple things that need to be fixed before we merge.

Fixed

2020-10-14 03:37 UTC, LoboMetalurgico approved these changes

2020-10-14 03:37 UTC, LoboMetalurgico commented
Thank You!

2020-10-14 03:38 UTC, merged