Fix dry sponge delete waterlogged block & Fix dry sponge can't absorb water at layer 1
PowerNukkit/PowerNukkit pull request #967
Opened 2021-02-15 12:30 UTC by GoodLucky777

Fix dry sponge delete waterlogged block (#643) & Fix dry sponge can't absorb water at layer 1 (#94, #430)

2021-02-15 12:48 UTC, RizenSoulja commented
Yesh!

2021-05-20 16:49 UTC, LoboMetalurgico requested changes
Hello! Thanks for your Pull Request, but for the tests I did, the sponge's behavior remains the same. Could you check this?

2021-05-28 13:05 UTC, roridev submitted a review, later dismissed

2021-05-28 13:05 UTC, roridev commented on src/main/java/cn/nukkit/block/BlockSponge.java
> +                    this.getLevel().setBlockStateAt(faceBlock.getX(), faceBlock.getY(), faceBlock.getZ(), 1, Block.get(BlockID.AIR));
The whole basis of this pull request relies on the change from `floorX` to `X` affecting the sponge's behaviour.

Why is that the case and why floored coordinates would be a problem?

As @LoboMetalurgico stated there is no reason why the simple change to exact coordinates would change any behaviour.

For this reason, until this change is explained or we're able to notice the fixes at all we can't merge this.

2021-05-30 06:13 UTC, GoodLucky777 commented
It was looping and also checking air so I fixed, Ready to be reviewed

2021-06-03 11:02 UTC, LoboMetalurgico approved these changes
Looks like everything is fine now. Thank you!

2021-06-03 11:03 UTC, merged